// =============================================================================
// tm_pipeline.v
//
// Minimal MFCC-to-Tsetlin-Machine simulation pipeline.
//
// Expected external files:
//   mem/mfcc_frames.mem        -> generated by wav_to_mfcc_mem.py
//   mem/binarizer_thresh.mem   -> generated by the Python training script
//   mem/tm_states.mem          -> generated by the Python training script
//
// Data flow:
//   mfcc_frame_source -> binarizer -> tm_classifier
// =============================================================================

`timescale 1ns / 1ps

module tm_pipeline #(
    parameter N_CLASSES  = 5,
    parameter MAX_FRAMES = 1024
)(
    input  wire       clk,
    input  wire       rst,
    input  wire       start,

    output wire       out_valid,
    output wire [2:0] out_class,

    output wire       frame_done,
    output wire       all_done,
    output wire [31:0] frame_number
);

    wire        mfcc_valid;
    wire [15:0] mfcc_data;
    wire [3:0]  mfcc_idx;

    wire        bin_valid;
    wire        bin_ready;
    wire        tm_ready;
    wire [103:0] features;

    mfcc_frame_source #(
        .MAX_FRAMES(MAX_FRAMES)
    ) src (
        .clk(clk),
        .rst(rst),
        .start(start),
        .out_ready(bin_ready),

        .out_valid(mfcc_valid),
        .out_data(mfcc_data),
        .out_idx(mfcc_idx),

        .frame_done(frame_done),
        .all_done(all_done),
        .frame_number(frame_number)
    );

    binarizer bin (
        .clk(clk),
        .rst(rst),
        .in_valid(mfcc_valid),
        .in_data(mfcc_data),
        .in_idx(mfcc_idx),
        .in_ready(bin_ready),

        .out_ready(tm_ready),
        .out_valid(bin_valid),
        .out_features(features)
    );

    tm_classifier tm (
        .clk(clk),
        .rst(rst),
        .in_valid(bin_valid),
        .in_features(features),
        .in_ready(tm_ready),

        .out_valid(out_valid),
        .out_class(out_class)
    );

endmodule
